---
name: actionlint
description: Run actionlint for all workflow files
author: Solkor Tech
branding:
  color: green
  icon: check-circle

runs:
  using: composite

  steps:
    - name: Add Problem Matcher
      shell: bash
      run: echo "::add-matcher::${{ github.action_path }}/matcher/actionlint.json"

    - name: Run actionlint
      uses: docker://docker.io/rhysd/actionlint:1.7.12@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667
      with:
        args: -color
